version: '3.8'

services:
  gallery:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GALLERY_PASSWORD=your-secret-password
      - SITE_TITLE=My Event Photos
      - PORT=8080
    volumes:
      - ./uploads:/root/uploads
    restart: unless-stopped